### PR TITLE
add support arm64 architecture

### PR DESCRIPTION
**Pull request by longquan7**
I was build this image on arm64 architecture and successed So I think it can be support arm64

### CODE REVIEW

**Comment by nicolas-albert** [comment]
Hi,
Thank you for your interest.
We have never test Convertigo on an **arm64** hardware, which do you use, a **Raspberry Pi** ?
With `FROM openjdk:8-jre`, Docker will automatically find the JDK here ? https://hub.docker.com/r/arm64v8/openjdk/

We will try to test it before a validation.

**Comment by longquan7** [comment]
@nicolas-albert OK.thanks, If test you can use From arm64v8/openjdk:8-jre

**Comment by longquan7** [comment]
@nicolas-albert This's merged ,So when we add it to https://hub.docker.com/u/arm64v8/ ?

**Comment by nicolas-albert** [comment]
Hi @longquan7 !
Our PR for the multiarch Convertigo is accepted 👍
https://hub.docker.com/_/convertigo/

I don't know why others arch images are still not available but it's a question of days.

We are curious about your usage of Convertigo. What kind of server do you use and want type of project to you run ?

Thank for your interest !

**Pull request merged**
